rm -f *.xml
rm -f *auction.yaml
rm -f *substation.yaml
rm -f *metrics.json
rm -f *.log
rm -f *_opf.csv
rm -f *_pf.csv
rm -f ercot_8.csv
rm -f *_FNCS_Config.txt
rm -f *_ercot.json
rm -f *_dict.json
rm -f weather*.json
rm -f *.zpl
rm -f *.h5
rm -f *.dat
