@startuml
class ThermoStatMode {
    UNDEFINED
    OFF
    COOLING
    HEATING
}

class HeatingSystemType {
    UNDEFINED
    NONE
    GAS
    ELECTRIC
    HEAT_PUMP
}

class CoolingSystemType {
    UNDEFINED
    NONE
    ELECTRIC
}

class WindowFrameType {
    UNDEFINED
    NONE
    ALUMINUM
    THERMAL_BREAK
    WOOD
    INSULATED
}

class WindowGlazingTreatment {
    UNDEFINED
    CLEAR
    ABS
    REFLECTIVE
}

class WindowGlassType {
    UNDEFINED
    OTHER
    NORMAL
    LOW_E
}

class SortDirection {
    ASCENDING
    DESCENDING
}

class HVACDSOTAgent {
    temperatures: Unknown
    schedule: Unknown
    forecasts: Unknown
    asset: Unknown
    flexibility: Unknown
    da_bidding_strategy: Unknown
    rt_bidding_strategy: Unknown
    helics_topic_map: dict
    calc_capacites_and_all_heat_flows()
}

class HVACTemperatures {
    validate_inputs()
}

class HVACSchedule {
    temperatures: Unknown
    validate_inputs()
    get_scheduled_setpoint(hour_of_day: int, day_of_week: int)
    change_basepoint(sim_time: <ast.Attribute object at 0x10563c190>, temperatures: HVACTemperatures, model_diag_level: int)
    calc_thermostat_settings(temperatures: HVACTemperatures, slider: float, model_diag_level: int)
}

class DSOT4pointBid {
    cumulative_curve: list
    points: list
    make_marginal_price_curve(price_direction: SortDirection)
}

class DSOTRTMarketinterface {
    clearing_price: list
    clearing_quantities: list
}

class DSOTDAMarketInterface {
}

class HVACDSOTAssetState {
    hvac_on: str
    thermostat_mode: Unknown
    copy_attributes_from(other_obj: object)
}

class ETPStructureParams {
    UA: str
    CA: str
    HM: str
    CM: str
}

class HVACDSOTStructureModel {
    glass_type: Unknown
    window_frame_type: Unknown
    glazing_treatment: Unknown
    etp_structure_params: Unknown
    validate_attributes()
    lookup_window_transmission_coefficient()
    lookup_Rwindow()
    calc_structure_areas()
    calc_solar_heatgain_factor()
    div(numerator: float, denominator: float, def_val_if_zero_denom: float)
    calc_UA()
    calc_CA()
    calc_HM()
    calc_CM()
    calc_structure_ETP_parameters()
}

class HVACDSOTEnvironmentModel {
    humidity_forecast: list
    internal_gain_forecast: list
    solar_gain_forecast: list
    thermostate_mode: Unknown
    structure_model: str
    copy_attributes_from(other_obj: object)
    calc_Qh(thermostat_mode: ThermoStatMode, hvac_on: bool, heating_capacity: float, cooling_capacity: float, hvac_kW: float)
    calc_Qi(house_kW: float, wh_kW: float, thermostat_mode: ThermoStatMode, hvac_on: bool, heating_capacity: float, cooling_capacity: float, hvac_kW: float, Qh_org: float)
    calc_Qs(solar_heatgain_factor: float, solar_gain: float)
    calc_Qa(house_kW: float, wh_kW: float, thermostat_mode: ThermoStatMode, hvac_on: bool, heating_capacity: float, cooling_capacity: float, hvac_kW: float, Qs: float, Qi: float, Qh: float, Qh_org: float)
    calc_Qm(house_kW: float, wh_kW: float, thermostat_mode: ThermoStatMode, hvac_on: bool, heating_capacity: float, cooling_capacity: float, hvac_kW: float, Qs: float, Qi: float)
    calc_all_heat_flows(house_kW: float, wh_kW: float, thermostat_mode: ThermoStatMode, hvac_on: bool, heating_capacity: float, cooling_capacity: float, hvac_kW: float)
    calc_solar_flux(cpt: str, day_of_yr: int, lat: float, sol_time: float, dnr_i: float, dhr_i: float, vertical_angle: float)
    calc_solargain(sim_time: <ast.Attribute object at 0x10584cdd0>, solar_direct: float, solar_diffuse: float)
}

class DSOTForecasts {
    solar_gain: list
    forecast_ziploads: str
    full_forecast_zipload: list
    internal_gain: str
    zipload: list
    inside_air_temperature: list
    calc_forecast_stats()
    calc_solar_gain_forecast(times: list, environment_model: HVACDSOTEnvironmentModel, solar_direct: list, solar_diffuse: list)
}

class HVACDSOTSystemModel {
    environment_model: Unknown
    forecasts: Unknown
    heating_cop_adj_da: list
    cooling_cop_adj_da: list
    validate_attributes()
    calc_heating_capacity()
    calc_cooling_capacity()
    calc_heating_COP()
    calc_cooling_COP()
    calc_design_capacities(etp_structure_params: ETPStructureParams, heating_system_type: HeatingSystemType, environment_model: HVACDSOTEnvironmentModel, structure_model: HVACDSOTStructureModel)
}

class HVACDSOTPriceFlexibilityCurve {
    get_flexible_price(quantity: float, DA_price_delta: float, hvac_kW: float, price_forecast: float)
}

class HVACDSOTBiddingStrategy {
    hvac_schedule: Unknown
    flexibility: Unknown
    bid: Unknown
}

class HVACDSOTDABiddingStrategy {
    forecasts: Unknown
    temperatures: Unknown
    system_model: Unknown
    asset_state: Unknown
    structure: Unknown
    etp_structure_params: Unknown
    bid_da: list
    temp_room: list
    temp_desired_48hour_cool: list
    temp_desired_48hour_heat: list
    latent_factor: list
    bid: Unknown
    update_forecast_temperature_limits()
    update_da_indoor_temperature_limits(cooling_setpt: float, heating_setpt: float)
    initialize_inside_air_temperature()
    update_da_temperature_limits(sim_time: <ast.Attribute object at 0x1058ebd50>)
    setup_da_temperature_parameters(sim_time: <ast.Attribute object at 0x1058f79d0>)
    estimate_required_cooling_quantity(time_idx: int)
    estimate_required_heating_quantity(time_idx: Unknown)
    get_uncntrl_hvac_load(sim_time: <ast.Attribute object at 0x10590ba50>)
    temperature_bound_rule(m: <ast.Attribute object at 0x10591a150>, t: int)
    obj_rule(m: <ast.Attribute object at 0x10591bfd0>)
    con_rule_eq1(m: <ast.Attribute object at 0x10592c590>, t: int)
    solve_for_da_optimal_quantities()
}

class HVACDSOTAssetModel {
    heating_system_type: Unknown
    cooling_system_type: Unknown
    forecasts: Unknown
    temperatures: Unknown
    environment_model: Unknown
    system_model: Unknown
    structure_model: Unknown
    asset_state: Unknown
    A_ETP: Unknown
    B_ETP_ON: Unknown
    B_ETP_OFF: Unknown
    AEI: Unknown
    CA: Unknown
    UA: Unknown
    CM: Unknown
    HM: Unknown
    Qa_On: Unknown
    Qa_Off: Unknown
    Qm: Unknown
    calc_AEI(environment_model: Unknown)
    simulate_time_step(state: HVACDSOTAssetState, environ: HVACDSOTEnvironmentModel, temperatures: HVACTemperatures, time_step_size: <ast.Attribute object at 0x105972450>)
}

class HVACDSOTAsset {
    asset_state: Unknown
    asset_model: Unknown
}

class HVACDSOTRTBiddingStrategy {
    period: Unknown
    RT_minute_count_interpolation: str
    quantity_curve: Unknown
    temp_curve: list
    asset_model: Unknown
    asset_state: Unknown
    temperatures: Unknown
    system_model: Unknown
    da_bidding_strategy: Unknown
    forecasts: Unknown
    interpolate_DA_quantities_into_RT()
    estimate_hvac_energy_in_rt_period()
    create_bid()
    form_rt_bid()
}

@enduml