#!/usr/bin/env python3
"""Generate a docker .env from scripts/grid_version and scripts/tesp_version.

Writes to scripts/docker/.env by default. Preserves optional variables and comments
from a template embedded here.

Usage:
  python3 scripts/docker/generate_env.py [--out PATH]
"""
from pathlib import Path
import argparse

ROOT = Path(__file__).resolve().parents[2]
SCRIPTS = Path(__file__).resolve().parent.parent / 'scripts'
DEFAULT_OUT = Path(__file__).resolve().parent / '.env'

parser = argparse.ArgumentParser()
parser.add_argument('--out', '-o', default=str(DEFAULT_OUT), help='Output .env path')
args = parser.parse_args()

grid_file = ROOT / 'scripts' / 'grid_version'
tesp_file = ROOT / 'scripts' / 'tesp_version'

if not grid_file.exists():
    raise SystemExit(f"grid_version file not found at {grid_file}")
if not tesp_file.exists():
    raise SystemExit(f"tesp_version file not found at {tesp_file}")

grid_ver = grid_file.read_text().strip()
tesp_ver = tesp_file.read_text().strip()

content = f"""# =============================================================================
# TESP Docker Configuration (auto-generated)
# =============================================================================
# This file is generated by scripts/docker/generate_env.py
# It merges the canonical defaults with version values from scripts/grid_version
# and scripts/tesp_version.

# -----------------------------------------------------------------------------
# Version Configuration
# -----------------------------------------------------------------------------
# Read from scripts/grid_version and scripts/tesp_version
VER={grid_ver}
TESP_VER={tesp_ver}

# -----------------------------------------------------------------------------
# User Configuration
# -----------------------------------------------------------------------------
SIM_UID=1001
SIM_GID=9002
SIM_USER=worker
SIM_GRP=runner

# -----------------------------------------------------------------------------
# Build Configuration
# -----------------------------------------------------------------------------
UBUNTU_VERSION=22.04

# Build directory (where build scripts are located)
# When running docker-compose from `scripts/docker/`, default to the repo-relative path
BUILD_DIR=../build

# CPLEX Configuration (optional)
CPLEX_BIN=cplex_studio129.linux-x86-64.bin

# -----------------------------------------------------------------------------
# Runtime Environment Variables
# -----------------------------------------------------------------------------
PSST_SOLVER=cbc
PSST_WARNING=ignore

# -----------------------------------------------------------------------------
# Network Configuration (Optional)
# -----------------------------------------------------------------------------
# HTTPS_PROXY=http://proxy01.pnl.gov:3128
# HTTP_PROXY=http://proxy01.pnl.gov:3128

# -----------------------------------------------------------------------------
# Volume Mount Paths (paths relative to repository root when running from scripts/docker)
# -----------------------------------------------------------------------------
HOST_EXAMPLES_DIR=../examples
HOST_DATA_DIR=../data
HOST_OUTPUT_DIR=../outputs

# -----------------------------------------------------------------------------
# Build Options
# -----------------------------------------------------------------------------
COMPOSE_DOCKER_CLI_BUILD=1
DOCKER_BUILDKIT=1
"""

out_path = Path(args.out)
out_path.write_text(content)
print(f'Wrote {out_path} with grid_version={grid_ver} and tesp_version={tesp_ver}')
