rm -f *.log
rm -f *.csv
rm -f *.out
rm -f *.xml
rm -f *.audit
rm -f *metrics*.*
rm -f *dict.json
rm -f *_gridlabd.json
rm -f *_substation.json
rm -f *_weather.json
rm -f *_gridlabd.txt
rm -f *_substation.yaml
rm -f *_weather_f.json
rm -f *.dat
rm -rf output
rm -f *.idf
rm -f *.bnd
