#!/bin/bash

if [[ -z ${TESPDIR} ]]; then
  echo "Edit tesp.env in the TESP directory"
  echo "Run 'source tesp.env' in that same directory"
  exit
fi

echo
echo "  This script iterates the examples directory calling clean.sh in tha directory."
echo "  A user can modify a particular directory clean.sh script if needed."

while true; do
    read -p "  Do you wish to clean all TESP examples? " yn
    case $yn in
        [Yy]* ) clean_me="clean"; break;;
        [Nn]* ) clean_me="leave"; break;;
        * ) echo "  Please answer [y]es or [n]o.";;
    esac
done

if [[ $clean_me == "clean" ]]; then
  CWD=$(pwd)

  echo "  Cleaning TESP examples:"
  cd "$TESPDIR/examples/capabilities" || exit
  for dir in *
  do
    if [ -d "$dir" ]
    then
      FILE=$dir/clean.sh
      if [ -f "$FILE" ]
      then
        echo "   /"$dir
        cd $dir || exit
        ./clean.sh
        cd ..
      fi
    fi
  done

  echo "   /sgip1"
  cd "$TESPDIR/examples/analysis/sgip1" || exit
#  ./clean.sh

  echo "   /dsot/code"
  cd "$TESPDIR/examples/analysis/dsot/code" || exit
#  ./clean.sh

  echo "   /consensus/code"
  cd "$TESPDIR/examples/analysis/consensus/code" || exit
#  ./clean.sh

  echo "   /build"
  cd "$TESPDIR/scripts/build" || exit
  ./clean.sh

  echo "   /test"
  cd "$TESPDIR/src/tesp_support/test/api" || exit
  ./clean.sh

  echo "  Done!"
  cd "$CWD" || exit
else
  echo "  Not cleaning TESP examples"
fi

