#!/bin/bash

CWD=$(pwd)

cd "$TESPDIR/examples/capabilities/loadshed" || exit
./clean.sh
make clean
cd ../loadshedf || exit
./clean.sh
cd ../energyplus || exit
./clean.sh
cd ../te30 || exit
./clean.sh
cd ../pypower || exit
./clean.sh
cd ../weatherAgent || exit
./clean.sh
cd ../dsostub || exit
./clean.sh
cd ../dsostubf || exit
./clean.sh
cd ../ieee8500 || exit
./clean.sh
cd PNNLteam || exit
 ./clean.sh
cd ../../comm || exit
rm -rf CombinedCase
rm -rf Nocomm_Base
rm -rf Eplus_Restaurant
rm -rf SGIP1c
rm -rf Eplus_Comm
cd ../ercot/case8 || exit
./clean.sh
rm -f ./*.glm
cd dsostub || exit
./clean.sh
cd ../../bulk_system || exit
./clean.sh
cd ../dist_system || exit
./clean.sh


cd "$TESPDIR/examples/analysis/sgip1" || exit
#./clean.sh
cd ../dsot/code || exit
#./clean.sh


cd "$CWD" || exit
