#!/usr/bin/python3
# Copyright (C) 2021-2022 Battelle Memorial Institute
# file: editconfig

import sys
import tesp_support.api as tesp

# normal command line argument is 'test.json'
tesp.make_tesp_case(sys.argv[1])
