#!/usr/bin/env python3
# Copyright (c) 2021-2025 Battelle Memorial Institute
# file: editconfig

import sys
import tesp_support.original.tesp_case as tesp

if len(sys.argv) > 0:
    tesp.make_tesp_case(sys.argv[1])
else:
    print("Usage:\n  'makecase test.json' -> Create TESP case using a json configuration file")
