#!/usr/bin/env python3
# Copyright (c) 2021-2025 Battelle Memorial Institute
# file: monte_carlo

# normal command line argument is 'case.json'
import sys
import tesp_support.original.tesp_case as tesp

tesp.make_monte_carlo_cases(sys.argv[1])

