#!/usr/bin/python3
# Copyright (C) 2021-2022 Battelle Memorial Institute
# file: monte_carlo

# normal command line argument is 'case.json'
import sys
import tesp_support.api as tesp

tesp.make_monte_carlo_cases(sys.argv[1])

