#!/bin/bash
# Copyright (C) 2021-2022 Battelle Memorial Institute
# file: testhelicsjava.sh

JAVAPATH=$INSTDIR/java

cd $TESPDIR/scripts/helpers

javac -classpath ".:$JAVAPATH/helics.jar" test_helics.java
java -classpath ".:$JAVAPATH/helics.jar" -Djava.library.path="$JAVAPATH" test_helics
