#!/bin/bash
# Copyright (C) 2021-2022 Battelle Memorial Institute
# file: testhelicsjava.sh

if [[ -z ${INSTDIR} ]]; then
  . "${HOME}/tespEnv"
fi

JAVAPATH=${INSTDIR}/java

cd "${TESPHELPR}"
javac -classpath ".:$JAVAPATH/helics.jar" test_helics.java
java -classpath ".:$JAVAPATH/helics.jar" -Djava.library.path="$JAVAPATH" test_helics
