pip3 install sphinx
pip3 install sphinx-autobuild
pip3 install recommonmark
pip3 install javasphinx
pip3 install sphinx-jsonschema
pip3 install sphinx_rtd_theme
pip3 install sphinxcontrib-bibtex
pip3 install urllib3
# make html
