# Copyright (C) 2025 Battelle Memorial Institute
# See LICENSE file at https://github.com/pnnl/tesp
# file: cd_builder.py
"""
Created on Wed Feb 5 11:55:32 2025

This script is used to build a PlantUML class diagram for a specified Python file.

The basis for this script was generated by ChatGPT 4o. 

@author: Trevor Hardy

"""

import ast
import os
import logging
import argparse
from pathlib import Path
import sys


class ClassDiagramGenerator(ast.NodeVisitor):
    def __init__(self):
        self.classes = {}

    def get_parameter_type(self, args, param_name):
        # Look for the type of the parameter if available
        for arg in args.args:
            if arg.arg == param_name:
                if args.args[0].arg == 'self':  # eliminate 'self'
                    index = args.args.index(arg) - 1
                else:
                    index = args.args.index(arg)
                if index < len(args.kwonlyargs) and args.kwonlyargs[index].annotation:
                    return ast.dump(args.kwonlyargs[index].annotation)
                if arg.annotation:
                    return arg.annotation.id
        return None


    def visit_ClassDef(self, node):
        class_name = node.name
        method_details = []
        attr_types = {}
        enum_values = []

        # Determine if the class is an Enum by checking base classes
        is_enum = any(base.id == 'Enum' for base in node.bases if isinstance(base, ast.Name))

        if is_enum:
            # Extract enumeration members
            for n in node.body:
                if isinstance(n, ast.Assign):
                    for target in n.targets:
                        if isinstance(target, ast.Name):
                            enum_values.append(target.id)
        else:
            # Extract methods and attributes
            init_method = None
            for n in node.body:
                if isinstance(n, ast.FunctionDef):
                    method_name = n.name
                    args_with_types = []

                    # Get argument types
                    for arg, annotation in zip(n.args.args[1:], n.args.args[1:]):  # Skip `self`
                        type_hint = annotation.annotation
                        if type_hint is None:
                            raise ValueError(f"Data type not defined for argument '{arg.arg}'" 
                                             f" in method '{method_name}' in class '{class_name}'")
                        elif isinstance(type_hint, ast.Name):
                            arg_type = type_hint.id
                        elif isinstance(type_hint, ast.Attribute):
                            arg_type = str(type_hint.value.id) + "." + str(type_hint.attr)
                        else:
                            arg_type = ast.unparse(type_hint) if hasattr(type_hint, 'id') else str(type_hint)
                        args_with_types.append((arg.arg, arg_type))

                    # Get return type
                    return_type = n.returns
                    if return_type is None:
                        return_type_hint = 'None'
                    elif isinstance(n.returns, ast.Constant) and n.returns.value is None:
                        return_type_hint = 'None'
                    else:
                        return_type_hint = ast.unparse(return_type) if hasattr(return_type, 'id') else str(return_type)

                    if method_name == '__init__':
                        init_method = n
                    else:
                        method_details.append((method_name, args_with_types, return_type_hint))

            self.extract_attributes(init_method, attr_types, class_name)

        self.classes[class_name] = {
            'attributes': attr_types,
            'methods': method_details,
            'enum_values': enum_values if is_enum else None
        }

        self.generic_visit(node)

    def extract_attributes(self, init_method: ast.AST, attr_types: list, class_name: str):
        if init_method:
            for stmt in init_method.body:
                if not isinstance(stmt, ast.Expr) and not isinstance(stmt, ast.If):
                # Don't need to do anything with func/method calls in __init__()
                    attr_type = None
                    if isinstance(stmt, ast.AnnAssign):
                        # For attributes with type annotations
                        attr_name = stmt.target.attr
                        if isinstance(stmt, ast.AnnAssign):
                            if hasattr(stmt.annotation, "id"):
                                # Annontation is a direct Python data type
                                attr_type = stmt.annotation.id
                            elif hasattr(stmt.annotation, "attr"):
                                # Annotation is some other data type, e.g. "dt.datetime"
                                attr_type = stmt.annotation.attr
                            else:
                                # Should only get here if something is wrong
                                attr_type = "unknown_annotation"
                    elif isinstance(stmt, ast.Assign):
                        # Date type is not annotated and needs to be inferred from assigned value
                        if hasattr(stmt, "targets"):
                            attr_name = stmt.targets[0].attr
                        else:
                            # Should only get here if something is wrong
                            attr_name = "unknown_name_inferred"
                        if hasattr(stmt.value, "func") and hasattr(stmt.value.func, "id"):
                            attr_type = stmt.value.func.id
                        elif isinstance(stmt.value, ast.Attribute):
                            if hasattr(stmt.value.value, "id"):
                                attr_type = stmt.value.value.id
                        elif isinstance(stmt.value, ast.Subscript):
                                attr_type = stmt.value.value.id
                        elif isinstance(stmt.value, ast.Dict):
                            attr_type = "dict"
                        elif isinstance(stmt.value, ast.List) or isinstance(stmt.value, ast.ListComp):
                            attr_type = "list"
                        elif isinstance(stmt.value, ast.Tuple):
                            attr_type = "tuple"
                        elif isinstance(stmt.value, ast.Name):
                            attr_type = self.get_parameter_type(init_method.args, stmt.value.id)
                        else:
                            # Should never get here
                            raise ValueError(f"Data type not defined for attribute '{attr_name}'" 
                                             f" in class '{class_name}'")
                            attr_type = "unknown_inferred"
                    else:
                        # Should only get here if something is wrong
                        attr_name = "unknown_else"
                        attr_type = "unknown_else" 
                   
                    attr_types[attr_name] = attr_type
                    # for target in stmt.targets:
                    #     if isinstance(target, ast.Attribute):
                    #         attr_name = target.attr
                    #         if hasattr(stmt, 'annotation'):
                    #             attr_type = ast.unparse(stmt.annotation)
                    #         elif isinstance(type(ast.literal_eval(stmt.value)), str):
                    #             attr_type = 'str' 
                    #         elif isinstance(type(ast.literal_eval(stmt.value)), float):
                    #             attr_type = 'float'
                    #         elif isinstance(stmt.value, ast.Num):
                    #             attr_type = 'int'
                    #         elif isinstance(stmt.value, ast.List):
                    #             attr_type = 'list'
                    #         elif isinstance(stmt.value, ast.Dict):
                    #             attr_type = 'dict'
                    #         elif isinstance(stmt.value, ast.Tuple):
                    #             attr_type = 'tuple'
                    #         else:
                    #             attr_type = 'Unknown'
                    #         attr_types[attr_name] = attr_type

    def generate_plantuml(self):
        lines = ["@startuml"]

        for class_name, details in self.classes.items():
            lines.append(f'class {class_name} {{')
            if details['enum_values'] is not None:
                for value in details['enum_values']:
                    lines.append(f'    {value}')
            else:
                for attr_name, attr_type in details['attributes'].items():
                    lines.append(f'    {attr_name}: {attr_type}')
                for method_name, args_with_types, return_type_hint in details['methods']:
                    arg_list = ", ".join([f"{name}: {typ}" for name, typ in args_with_types])
                    lines.append(f'    {method_name}({arg_list}): {return_type_hint}')
            lines.append('}\n')

        lines.append("@enduml")
        return "\n".join(lines)




def _auto_run(args):
    input_file_path = Path(myargs.input_python_script_path) #/ args.input_python_script_file
    output_file_path = Path(myargs.output_plantuml_file)
    with open(input_file_path, 'r', encoding='utf-8') as file:
        tree = ast.parse(file.read())
    
    generator = ClassDiagramGenerator()
    generator.visit(tree)
    plantuml_output = generator.generate_plantuml()
    with open(output_file_path, 'w', encoding='utf-8') as file:
        file.write(plantuml_output)


if __name__ == '__main__':
    # This slightly complex mess allows lower importance messages
    # to be sent to the log file and ERROR messages to additionally
    # be sent to the console as well. Thus, when bad things happen
    # the user will get an error message in both places which,
    # hopefully, will aid in trouble-shooting.
    fileHandle = logging.FileHandler("cd_builder.log",'w')
    fileHandle.setLevel(logging.DEBUG)
    streamHandle = logging.StreamHandler(sys.stdout)
    streamHandle.setLevel(logging.ERROR)
    logging.basicConfig(level=logging.DEBUG,
                        handlers=[fileHandle, streamHandle])
    parser = argparse.ArgumentParser(description= "Creates PlantUML class diagram from specified file")
    parser.add_argument('-i', '--input_python_script_path',
                        help="Path to Python script to build class diagram from",
                        nargs='?',
                        default="/Users/hard312/src/TSP/tesp/src/tesp_support/tesp_support/dsot/hvac_new_agent.py")
    # parser.add_argument('-f', '--input_python_script_file',
    #                     help="Python script to build class diagram from",
    #                     nargs='?',
    #                     default="hvac_new_agent.py")
    parser.add_argument('-o', '--output_plantuml_file',
                        help="configuration JSON for the HVAC agnet",
                        nargs='?',
                        default="hvac_agent_class_definitions.plantuml")
    myargs = parser.parse_args()
    _auto_run(myargs)