@startuml

!include ./hvac_agent_class_definitions.plantuml

HVACDSOTAgent "1" *-- "1" HVACDSOTRTBiddingStrategy
HVACDSOTAgent "1" *-- "1" HVACDSOTDABiddingStrategy
HVACDSOTAgent "1" *-- "1" DSOTRTMarketInterface
HVACDSOTAgent "1" *-- "1" DSOTDAMarketInterface
HVACDSOTAgent "1" *-- "1" HVACDSOTAsset
HVACDSOTAgent "1" *-- "1" HVACSchedule
HVACDSOTAgent "1" *-- "1" HVACTemperatures
HVACDSOTAgent "1" *-- "1" DSOTForecasts
HVACDSOTAgent "1" *-- "1" HVACDSOTPriceFlexibilityCurve


HVACDSOTAsset "1" *-- "1" HVACDSOTAssetModel 
HVACDSOTAsset "1" *-- "1" HVACDSOTAssetState

DSOTRTMarketInterface "1" *-- "1" DSOTRTMarketStateMachine
DSOTDAMarketInterface "1" *-- "1" DSOTDAMarketStateMachine
HVACDSOTRTBiddingStrategy "1" *-- "1" DSOT4pointBid
HVACDSOTDABiddingStrategy "48" *-- "1" DSOT4pointBid
HVACDSOTAssetModel "1" *-- "1" HVACDSOTEnvironmentModel
HVACDSOTAssetState "1" *-- "1" ThermostatModeEnum
HVACDSOTAssetModel "1" *-- "1" HeatingSystemEnum
HVACDSOTAssetModel "1" *-- "1" CoolingSystemEnum
HVACDSOTAssetModel "1" *-- "1"  HVACDSOTSystemModel
HVACDSOTAssetModel "1" *-- "1"  HVACDSOTStructureModel
HVACDSOTStructureModel "1" *-- "1"  WindowFrameTypeEnum
HVACDSOTStructureModel "1" *-- "1"  WindowGlazingTreatmentEnum
HVACDSOTStructureModel "1" *-- "1"  WindowGlassTypeEnum
HVACDSOTStructureModel "1" *-- "1" ETPStructureParams



@enduml