participant User 
participant HVACDSOTAgent 
participant HVACDSOTAssetState
participant HVACDSOTSystemModel
participant HVACDSOTStructureModel
participant HVACDSOTRTBiddingStrategy

User -> HVACDSOTAgent: __init__(attributes)
activate HVACDSOTAgent #LightGrey
activate HVACDSOTAssetState #LightGrey
activate HVACDSOTSystemModel #LightGrey
activate HVACDSOTStructureModel #LightGrey
activate HVACDSOTRTBiddingStrategy #LightGrey

HVACDSOTAgent -> HVACDSOTAssetState: update_asset_state()
HVACDSOTAgent -> HVACDSOTAgent: calc_capacities_and_all_heat_flows()
activate HVACDSOTAgent #Red
HVACDSOTAgent -> HVACDSOTSystemModel: calc_cooling_capacity()
HVACDSOTAgent -> HVACDSOTSystemModel: calc_heating_capacity()
deactivate HVACDSOTAgent
HVACDSOTAgent -> HVACDSOTStructureModel: calc_structure_ETP_parameters()
activate HVACDSOTStructureModel #Red
HVACDSOTStructureModel -> HVACDSOTStructureModel: calc_UA()
HVACDSOTStructureModel -> HVACDSOTStructureModel: calc_CA()
HVACDSOTStructureModel -> HVACDSOTStructureModel: calc_HM()
HVACDSOTStructureModel -> HVACDSOTStructureModel: calc_CM()
HVACDSOTAgent -> HVACDSOTRTBiddingStrategy: form_rt_bid()
activate HVACDSOTRTBiddingStrategy #Red
HVACDSOTRTBiddingStrategy -> HVACDSOTRTBiddingStrategy: interpolate_da_quantities_into_RT()
HVACDSOTRTBiddingStrategy -> HVACDSOTRTBiddingStrategy: estimate_hvac_energy_in_rt_period()
HVACDSOTRTBiddingStrategy -> HVACDSOTRTBiddingStrategy: create_bid()
HVACDSOTAgent <-- HVACDSOTRTBiddingStrategy: rt_bid_obj
