@startuml

participant User 
participant HVACDSOTAgent 
participant HVACTemperatures
participant HVACSchedule
participant DSOTForecasts
participant HVACDSOTAsset
participant HVACDSOTAssetState
participant HVACDSOTAssetModel
participant HVACDSOTEnvironmentModel
participant HVACDSOTSystemModel
participant HVACDSOTStructureModel
participant HVACDSOTPriceFlexibiiltyCurve
participant HVACDSOTDABiddingStrategy
participant HVACDSOTRTBiddingStrategy

User -> HVACDSOTAgent: __init__(attributes)
activate HVACDSOTAgent #LightGrey
HVACDSOTAgent -> HVACDSOTAgent: init_class_attributes()

HVACDSOTAgent -> HVACTemperatures: __init__(attributes)
activate HVACTemperatures #LightGrey
HVACTemperatures -> HVACTemperatures: init_class_attributes()
HVACDSOTAgent <-- HVACTemperatures: temperatures_obj

HVACDSOTAgent -> HVACSchedule: __init__(attributes,\ntemperatures_obj)
activate HVACSchedule #LightGrey
HVACSchedule -> HVACSchedule: init_class_attributes()
HVACDSOTAgent <-- HVACSchedule: schedule_obj

HVACDSOTAgent -> DSOTForecasts: __init__(attributes)
activate DSOTForecasts #LightGrey
DSOTForecasts -> DSOTForecasts: init_class_attributes()
DSOTForecasts -> DSOTForecasts: calc_forecasts_stats()
HVACDSOTAgent <-- DSOTForecasts: forecasts_obj

HVACDSOTAgent -> HVACDSOTAsset: __init__(attributes,\nforecasts_obj,\ntemperatures_obj)
activate HVACDSOTAsset #LightGrey
HVACDSOTAsset -> HVACDSOTAsset: init_class_attributes()
HVACDSOTAsset -> HVACDSOTAssetState: __init__(attributes)
activate HVACDSOTAssetState #LightGrey
HVACDSOTAsset <-- HVACDSOTAssetState: asset_state_obj
HVACDSOTAsset -> HVACDSOTAssetModel: __init__(attributes,\ntemperature_obj,\nasset_state_obj,\nforecasts_obj,\nthermostat_mode)
activate HVACDSOTAssetModel #LightGrey
HVACDSOTAssetModel -> HVACDSOTEnvironmentModel: __init__(attributes,\nthermostat_mode,\nforecasts_obj)
activate HVACDSOTEnvironmentModel #LightGrey
HVACDSOTAssetModel <-- HVACDSOTEnvironmentModel: environment_model_obj
HVACDSOTAssetModel -> HVACDSOTSystemModel: __init__(attributes,\nenvironment_model_obj,\nforecasts_obj)
activate HVACDSOTSystemModel #LightGrey
HVACDSOTSystemModel -> HVACDSOTSystemModel: __init__(attributes)
HVACDSOTSystemModel -> HVACDSOTSystemModel: validate_attributes()
HVACDSOTAssetModel <-- HVACDSOTSystemModel: system_model_obj
HVACDSOTAssetModel -> HVACDSOTStructureModel: __init__(attributes)
activate HVACDSOTStructureModel #LightGrey
HVACDSOTStructureModel -> HVACDSOTStructureModel: __init__(attributes)
HVACDSOTStructureModel -> HVACDSOTStructureModel: validate_attributes()
HVACDSOTStructureModel -> HVACDSOTStructureModel: calc_structure_areas()
HVACDSOTStructureModel -> HVACDSOTStructureModel: lookup_Rwindow()
HVACDSOTStructureModel -> HVACDSOTStructureModel: lookup_window_transmission_coefficient()
HVACDSOTStructureModel -> HVACDSOTStructureModel: calc_structure_ETP()
activate HVACDSOTStructureModel #Red
HVACDSOTStructureModel -> HVACDSOTStructureModel: calc_UA()
HVACDSOTStructureModel -> HVACDSOTStructureModel: calc_CA()
HVACDSOTStructureModel -> HVACDSOTStructureModel: calc_HM()
HVACDSOTStructureModel -> HVACDSOTStructureModel: calc_CM()
HVACDSOTAssetModel <-- HVACDSOTStructureModel: structure_model_obj
deactivate HVACDSOTStructureModel
HVACDSOTAssetModel -> HVACDSOTSystemModel: calc_design_capacities()
HVACDSOTAsset <-- HVACDSOTAssetModel: asset_model_obj
HVACDSOTAgent <-- HVACDSOTAsset: asset_obj

HVACDSOTAgent -> HVACDSOTPriceFlexibiiltyCurve: __init__()
activate HVACDSOTPriceFlexibiiltyCurve #LightGrey
HVACDSOTAgent <-- HVACDSOTPriceFlexibiiltyCurve: price_flexibility_obj

HVACDSOTAgent -> HVACDSOTDABiddingStrategy: __init__(attributes,\nschedule_obj,\nflexibility_obj,\nforecasts_obj,\ntemperatures_obj,\nsystem_model_obj,\nasset_state_obj,\nasset_model_obj,\nstucture_model_obj)
activate HVACDSOTDABiddingStrategy #LightGrey
HVACDSOTDABiddingStrategy -> HVACDSOTDABiddingStrategy: init_class_attributes()
HVACDSOTAgent <-- HVACDSOTDABiddingStrategy: da_bidding_strategy_obj

HVACDSOTAgent -> HVACDSOTRTBiddingStrategy: __init__(attributes,period,\nschedule_obj,\nflexibility_obj,\nsasset_model_obj,\nasset_state_obj,\ntemperatures_obj,\nsystem_model_obj,\nda_bidding_strategy_obj,\nforecasts_obj)
activate HVACDSOTRTBiddingStrategy #LightGrey
HVACDSOTRTBiddingStrategy -> HVACDSOTRTBiddingStrategy: init_class_attributes()
HVACDSOTAgent <-- HVACDSOTRTBiddingStrategy: rt_bidding_strategy_obj

User <-- HVACDSOTAgent: hvac_agent_obj

@enduml 