#!/usr/bin/env python3
"""Build hourly actual DA quantity CSV from DSOT case forecast outputs.

This helper reconstructs actual hourly DA quantities using files created by
`tesp_support.dsot.plots.dso_forecast_stats`:

- DA_Q_forecast.csv
- DA_Q_error.csv

From dso_forecast_stats:
    error = (forecast - actual) / actual
so:
    actual = forecast / (1 + error)

The resulting CSV can be used as `--actual-csv` for
`calibrate_q_bid_forecast_correction.py`.

-------------------------------------------------------------------------------
Note: this script was generated by an AI assistant to reproduce the DA quantity 
forecast process used in previous iterations of the DSOT analysis.
-------------------------------------------------------------------------------     

"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd


def read_timeseries_csv(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path, index_col=0, parse_dates=True)
    if not isinstance(df.index, pd.DatetimeIndex):
        raise ValueError(f"{path}: index is not datetime after parsing")
    if df.index.has_duplicates:
        df = df.groupby(level=0).mean(numeric_only=True)
    return df.sort_index()


def reconstruct_actual_da_quantities(
    case_path: Path,
    forecast_file: str = "DA_Q_forecast.csv",
    error_file: str = "DA_Q_error.csv",
    output_file: str = "actual_da_q.csv",
    drop_total: bool = False,
) -> Path:
    """Reconstruct hourly actual DA quantities from forecast and error files.

    Returns:
        Path to the generated CSV.
    """
    forecast_path = case_path / forecast_file
    error_path = case_path / error_file
    output_path = case_path / output_file

    if not forecast_path.exists():
        raise FileNotFoundError(f"Missing forecast file: {forecast_path}")
    if not error_path.exists():
        raise FileNotFoundError(f"Missing error file: {error_path}")

    forecast_df = read_timeseries_csv(forecast_path)
    error_df = read_timeseries_csv(error_path)

    common_index = forecast_df.index.intersection(error_df.index)
    common_cols = [c for c in forecast_df.columns if c in error_df.columns]

    if len(common_index) == 0:
        raise ValueError("No overlapping timestamps between forecast and error files")
    if len(common_cols) == 0:
        raise ValueError("No overlapping columns between forecast and error files")

    f = forecast_df.loc[common_index, common_cols]
    e = error_df.loc[common_index, common_cols]

    denom = 1.0 + e
    near_zero = denom.abs() < 1e-9
    if near_zero.any().any():
        count = int(near_zero.sum().sum())
        raise ValueError(
            f"Encountered {count} sample(s) where 1 + error is ~0; cannot reconstruct actual value safely."
        )

    actual_df = f / denom

    if drop_total and "Total" in actual_df.columns:
        actual_df = actual_df.drop(columns=["Total"])

    actual_df = actual_df.replace([np.inf, -np.inf], np.nan).dropna(how="any")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    actual_df.to_csv(output_path)
    return output_path


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Reconstruct actual DA quantities from DA_Q_forecast.csv and DA_Q_error.csv"
    )
    parser.add_argument(
        "--case-path",
        required=True,
        help="Path to DSOT case folder containing DA_Q_forecast.csv and DA_Q_error.csv",
    )
    parser.add_argument(
        "--forecast-file",
        default="DA_Q_forecast.csv",
        help="Forecast CSV filename inside --case-path (default: DA_Q_forecast.csv)",
    )
    parser.add_argument(
        "--error-file",
        default="DA_Q_error.csv",
        help="Error CSV filename inside --case-path (default: DA_Q_error.csv)",
    )
    parser.add_argument(
        "--output-file",
        default="actual_da_q.csv",
        help="Output CSV filename inside --case-path (default: actual_da_q.csv)",
    )
    parser.add_argument(
        "--drop-total",
        action="store_true",
        help="Drop 'Total' column from output if present.",
    )

    args = parser.parse_args()

    case_path = Path(args.case_path)
    output_path = reconstruct_actual_da_quantities(
        case_path=case_path,
        forecast_file=args.forecast_file,
        error_file=args.error_file,
        output_file=args.output_file,
        drop_total=args.drop_total,
    )

    print(f"Wrote reconstructed actual DA quantities: {output_path}")
    actual_df = read_timeseries_csv(output_path)
    print(f"Rows: {len(actual_df)}, Columns: {len(actual_df.columns)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
