#!/usr/bin/env python3
"""Merge calibrated Q-bid correction parameters into a JSON5 case config.

This utility updates only the `Q_bid_forecast_correction` block and writes a
new config file, leaving the source config unchanged.

It also writes a comparison report with old/new/delta values for:
- Q_gain
- t_65
- t_65_2
- DC_change_Q_DA

-------------------------------------------------------------------------------
Note: this script was generated by an AI assistant to reproduce the forecast
correction calibration process used in previous iterations of the DSOT analysis.
-------------------------------------------------------------------------------      
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


def _remove_json5_comments(text: str) -> str:
    # Remove block comments first.
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    # Remove line comments outside of string context (best-effort).
    out = []
    in_string = False
    quote_char = ""
    escaped = False
    i = 0
    while i < len(text):
        ch = text[i]
        nxt = text[i + 1] if i + 1 < len(text) else ""

        if in_string:
            out.append(ch)
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == quote_char:
                in_string = False
            i += 1
            continue

        if ch in ('"', "'"):
            in_string = True
            quote_char = ch
            out.append(ch)
            i += 1
            continue

        if ch == "/" and nxt == "/":
            while i < len(text) and text[i] not in "\r\n":
                i += 1
            continue

        out.append(ch)
        i += 1

    return "".join(out)


def _remove_trailing_commas(text: str) -> str:
    return re.sub(r",\s*([}\]])", r"\1", text)


def _find_matching_brace(text: str, start_index: int) -> int:
    depth = 0
    in_string = False
    quote_char = ""
    escaped = False

    for i in range(start_index, len(text)):
        ch = text[i]

        if in_string:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == quote_char:
                in_string = False
            continue

        if ch in ('"', "'"):
            in_string = True
            quote_char = ch
            continue

        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return i

    raise ValueError("No matching closing brace found")


def extract_qbid_block(config_text: str) -> tuple[int, int, str]:
    key_match = re.search(r'"Q_bid_forecast_correction"\s*:\s*', config_text)
    if not key_match:
        raise ValueError('Could not find key "Q_bid_forecast_correction" in config')

    open_brace = config_text.find("{", key_match.end())
    if open_brace < 0:
        raise ValueError('Could not find object start for "Q_bid_forecast_correction"')

    close_brace = _find_matching_brace(config_text, open_brace)
    block = config_text[open_brace : close_brace + 1]
    return open_brace, close_brace, block


def parse_json5_object_block(block_text: str) -> dict[str, Any]:
    cleaned = _remove_json5_comments(block_text)
    cleaned = _remove_trailing_commas(cleaned)
    return json.loads(cleaned)


def merge_qbid(old_block: dict[str, Any], new_block: dict[str, Any]) -> dict[str, Any]:
    merged = dict(old_block)
    # Keep existing default unless explicitly desired otherwise.
    for key, value in new_block.items():
        if key.startswith("DSO_"):
            merged[key] = value
    return merged


def _safe_pair(values: Any) -> list[float]:
    if isinstance(values, list) and len(values) >= 2:
        return [float(values[0]), float(values[1])]
    return [float("nan"), float("nan")]


def build_diff_report(old_block: dict[str, Any], merged_block: dict[str, Any]) -> dict[str, Any]:
    report: dict[str, Any] = {
        "summary": {
            "dsos_updated": 0,
            "parameters_compared": ["Q_gain", "t_65", "t_65_2", "DC_change_Q_DA"],
        },
        "by_dso": {},
    }

    compared = 0
    for key in sorted(merged_block.keys()):
        if not key.startswith("DSO_"):
            continue

        old = old_block.get(key, {})
        new = merged_block.get(key, {})

        dso_diff: dict[str, Any] = {
            "correct_old": old.get("correct"),
            "correct_new": new.get("correct"),
            "params": {},
        }

        for p in ["Q_gain", "t_65", "t_65_2", "DC_change_Q_DA"]:
            old_pair = _safe_pair(old.get(p))
            new_pair = _safe_pair(new.get(p))
            delta_pair = [new_pair[0] - old_pair[0], new_pair[1] - old_pair[1]]
            dso_diff["params"][p] = {
                "old": old_pair,
                "new": new_pair,
                "delta": delta_pair,
            }

        report["by_dso"][key] = dso_diff
        compared += 1

    report["summary"]["dsos_updated"] = compared
    return report


def render_qbid_block(merged_block: dict[str, Any], indent_spaces: int = 2) -> str:
    return json.dumps(merged_block, indent=indent_spaces)


def merge_calibration_into_config(
    source_config_json5: Path,
    calibration_json: Path,
    output_config_json5: Path,
    report_json: Path,
) -> tuple[Path, Path]:
    config_text = source_config_json5.read_text(encoding="utf-8")
    calibration = json.loads(calibration_json.read_text(encoding="utf-8"))

    start, end, old_block_text = extract_qbid_block(config_text)
    old_block = parse_json5_object_block(old_block_text)

    merged_block = merge_qbid(old_block, calibration)
    merged_block_text = render_qbid_block(merged_block, indent_spaces=2)

    updated_config_text = config_text[:start] + merged_block_text + config_text[end + 1 :]

    output_config_json5.parent.mkdir(parents=True, exist_ok=True)
    output_config_json5.write_text(updated_config_text, encoding="utf-8")

    report = build_diff_report(old_block, merged_block)
    report_json.parent.mkdir(parents=True, exist_ok=True)
    report_json.write_text(json.dumps(report, indent=2), encoding="utf-8")

    return output_config_json5, report_json


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Merge calibrated Q_bid_forecast_correction into a new JSON5 config file"
    )
    parser.add_argument("--source-config", required=True, help="Source rates_config.json5 path")
    parser.add_argument("--calibration-json", required=True, help="Calibrated Q-bid JSON path")
    parser.add_argument("--output-config", required=True, help="Output calibrated JSON5 path")
    parser.add_argument("--report-json", required=True, help="Output diff report JSON path")

    args = parser.parse_args()

    cfg, rep = merge_calibration_into_config(
        source_config_json5=Path(args.source_config),
        calibration_json=Path(args.calibration_json),
        output_config_json5=Path(args.output_config),
        report_json=Path(args.report_json),
    )

    print(f"Wrote calibrated config: {cfg}")
    print(f"Wrote calibration diff report: {rep}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
