#!/usr/bin/env python3
"""Calibrate Q_bid_forecast_correction coefficients per DSO.

This script fits the same model used in
`tesp_support.dsot.forecasting.Forecasting.correcting_Q_forecast_10_AM`:

    new_Q = Q_10_AM * Q_gain + t_65 * t_65_gain + t_65^2 * t_65_2_gain + DC_change_Q_DA

where:
- t_65 = |temperature_F - 65|
- coefficients are fit separately for weekday and weekend

Inputs are hourly time-series CSV files:
1) baseline quantity (proxy for uncorrected Q_10_AM target-hour quantities)
2) actual quantity (target realized quantity)
3) temperature (F by default, optionally C)

By default, all DSOs use the same temperature column. A per-DSO temperature
column template can also be provided.

For DSOT weather.dat inputs:
- weather.dat is a CSV-like file with a `temperature` column.
- if values are in Celsius, set `--temperature-unit C`.

Example:
    python calibrate_q_bid_forecast_correction.py \
      --baseline-csv C:/case/DA_Q_forecast.csv \
      --actual-csv C:/case/actual_da_q.csv \
      --temperature-csv C:/case/temperature_hourly.csv \
      --output C:/case/Q_bid_forecast_correction_calibrated.json


-------------------------------------------------------------------------------
Note: this script was generated by an AI assistant to reproduce the forecast
correction calibration process used in previous iterations of the DSOT analysis.
-------------------------------------------------------------------------------      
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd


DSO_PATTERNS = [
    re.compile(r"^DSO[ _]?(\d+)$", re.IGNORECASE),
    re.compile(r"^da_q(\d+)$", re.IGNORECASE),
    re.compile(r"^Bus[ _]?(\d+)$", re.IGNORECASE),
]


@dataclass
class FitResult:
    gain_q: float
    gain_t65: float
    gain_t65_2: float
    dc_change: float
    rmse: float
    n_samples: int


def read_timeseries_csv(path: Path) -> pd.DataFrame:
    """Read a CSV with a datetime index in column 0."""
    df = pd.read_csv(path, index_col=0, parse_dates=True)
    if not isinstance(df.index, pd.DatetimeIndex):
        raise ValueError(f"{path}: index is not datetime after parsing")
    df = df.sort_index()
    # Ensure hourly alignment if source has duplicate timestamps.
    if df.index.has_duplicates:
        df = df.groupby(level=0).mean(numeric_only=True)
    return df


def parse_dso_id(column_name: str) -> Optional[int]:
    for pattern in DSO_PATTERNS:
        match = pattern.match(column_name.strip())
        if match:
            return int(match.group(1))
    return None


def map_dso_columns(df: pd.DataFrame) -> Dict[int, str]:
    mapping: Dict[int, str] = {}
    for col in df.columns:
        dso = parse_dso_id(str(col))
        if dso is not None:
            mapping[dso] = col
    return mapping


def choose_temperature_series(
    temp_df: pd.DataFrame,
    dso_id: int,
    default_col: Optional[str],
    col_template: Optional[str],
) -> pd.Series:
    if col_template:
        candidate = col_template.format(dso=dso_id)
        if candidate in temp_df.columns:
            return temp_df[candidate]

    if default_col and default_col in temp_df.columns:
        return temp_df[default_col]

    # Fallback to single-column temperature files.
    if len(temp_df.columns) == 1:
        return temp_df.iloc[:, 0]

    raise ValueError(
        f"No temperature column found for DSO {dso_id}. "
        f"Tried template/default and no single-column fallback available."
    )


def to_fahrenheit(series: pd.Series, unit: str) -> pd.Series:
    u = unit.upper()
    if u == "F":
        return series
    if u == "C":
        return series * 9.0 / 5.0 + 32.0
    raise ValueError(f"Unsupported temperature unit: {unit}. Expected 'F' or 'C'.")


def fit_coefficients(
    baseline_q: pd.Series,
    actual_q: pd.Series,
    temperature_f: pd.Series,
    min_samples: int,
) -> Tuple[FitResult, FitResult]:
    """Fit weekday/weekend coefficients using least squares."""
    df = pd.DataFrame(
        {
            "baseline_q": baseline_q,
            "actual_q": actual_q,
            "temperature_f": temperature_f,
        }
    ).dropna()

    if df.empty:
        raise ValueError("No overlapping non-null samples after alignment")

    df["t65"] = (df["temperature_f"] - 65.0).abs()
    df["t65_2"] = df["t65"] ** 2
    # Monday=0 ... Sunday=6, matching pandas convention.
    weekday_mask = df.index.dayofweek <= 4

    def fit_subset(mask: pd.Series, label: str) -> FitResult:
        subset = df.loc[mask]
        n = len(subset)
        if n < min_samples:
            raise ValueError(
                f"Insufficient {label} samples for fit: {n} < {min_samples}. "
                "Provide more data or reduce --min-samples."
            )

        x = np.column_stack(
            [
                subset["baseline_q"].to_numpy(),
                subset["t65"].to_numpy(),
                subset["t65_2"].to_numpy(),
                np.ones(n),
            ]
        )
        y = subset["actual_q"].to_numpy()

        coeffs, _, _, _ = np.linalg.lstsq(x, y, rcond=None)
        y_hat = x @ coeffs
        rmse = float(np.sqrt(np.mean((y - y_hat) ** 2)))

        return FitResult(
            gain_q=float(coeffs[0]),
            gain_t65=float(coeffs[1]),
            gain_t65_2=float(coeffs[2]),
            dc_change=float(coeffs[3]),
            rmse=rmse,
            n_samples=n,
        )

    weekday_fit = fit_subset(weekday_mask, "weekday")
    weekend_fit = fit_subset(~weekday_mask, "weekend")
    return weekday_fit, weekend_fit


def build_output(
    fits: Dict[int, Tuple[FitResult, FitResult]],
    include_diagnostics: bool,
) -> Dict[str, object]:
    payload: Dict[str, object] = {"default": {"correct": False}}

    for dso in sorted(fits):
        wkday, wkend = fits[dso]
        item: Dict[str, object] = {
            "correct": True,
            "Q_gain": [wkday.gain_q, wkend.gain_q],
            "t_65": [wkday.gain_t65, wkend.gain_t65],
            "t_65_2": [wkday.gain_t65_2, wkend.gain_t65_2],
            "DC_change_Q_DA": [wkday.dc_change, wkend.dc_change],
        }
        if include_diagnostics:
            item["_fit_diagnostics"] = {
                "weekday": {"rmse": wkday.rmse, "n_samples": wkday.n_samples},
                "weekend": {"rmse": wkend.rmse, "n_samples": wkend.n_samples},
            }
        payload[f"DSO_{dso}"] = item

    return payload


def parse_dso_list(raw: Optional[str]) -> Optional[List[int]]:
    if raw is None or raw.strip() == "":
        return None
    return [int(x.strip()) for x in raw.split(",") if x.strip()]


def calibrate_q_bid_forecast_correction(
    baseline_csv: Path,
    actual_csv: Path,
    temperature_csv: Optional[Path] = None,
    temperature_csv_template: Optional[str] = None,
    temperature_column: Optional[str] = None,
    temperature_column_template: Optional[str] = None,
    temperature_unit: str = "F",
    dsos: Optional[List[int]] = None,
    min_samples: int = 72,
    include_diagnostics: bool = False,
    output: Optional[Path] = None,
) -> Tuple[Dict[str, object], Dict[int, Tuple[FitResult, FitResult]]]:
    """Calibrate DSO forecast-correction coefficients.

    Returns:
        Tuple of (json_payload, fit_results_by_dso).
    """
    baseline_df = read_timeseries_csv(baseline_csv)
    actual_df = read_timeseries_csv(actual_csv)
    if temperature_csv is None and not temperature_csv_template:
        raise ValueError("Either temperature_csv or temperature_csv_template must be provided")

    temp_df: Optional[pd.DataFrame] = None
    if temperature_csv is not None:
        temp_df = read_timeseries_csv(temperature_csv)

    baseline_map = map_dso_columns(baseline_df)
    actual_map = map_dso_columns(actual_df)

    common_dsos = sorted(set(baseline_map.keys()) & set(actual_map.keys()))
    if dsos is None:
        dso_ids = common_dsos
    else:
        dso_ids = [d for d in dsos if d in common_dsos]

    if not dso_ids:
        raise ValueError(
            "No DSOs available to calibrate. Check column naming in baseline/actual CSV files. "
            "Expected patterns include DSO_1, DSO 1, da_q1, Bus1."
        )

    fits: Dict[int, Tuple[FitResult, FitResult]] = {}
    for dso in dso_ids:
        baseline_col = baseline_map[dso]
        actual_col = actual_map[dso]

        if temperature_csv_template:
            dso_temp_path = Path(temperature_csv_template.format(dso=dso))
            dso_temp_df = read_timeseries_csv(dso_temp_path)
            temp_series = choose_temperature_series(
                dso_temp_df,
                dso,
                default_col=temperature_column,
                col_template=temperature_column_template,
            )
        else:
            if temp_df is None:
                raise ValueError("Shared temperature dataframe is not available")
            temp_series = choose_temperature_series(
                temp_df,
                dso,
                default_col=temperature_column,
                col_template=temperature_column_template,
            )

        temp_series = to_fahrenheit(temp_series, temperature_unit)

        wkday, wkend = fit_coefficients(
            baseline_df[baseline_col],
            actual_df[actual_col],
            temp_series,
            min_samples=min_samples,
        )
        fits[dso] = (wkday, wkend)

    output_payload = build_output(fits, include_diagnostics=include_diagnostics)

    if output is not None:
        output.parent.mkdir(parents=True, exist_ok=True)
        with output.open("w", encoding="utf-8") as fp:
            json.dump(output_payload, fp, indent=2)

    return output_payload, fits


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Calibrate Q_bid_forecast_correction coefficients per DSO."
    )
    parser.add_argument("--baseline-csv", required=True, help="Hourly baseline Q CSV path")
    parser.add_argument("--actual-csv", required=True, help="Hourly actual Q CSV path")
    parser.add_argument(
        "--temperature-csv",
        required=False,
        default=None,
        help="Shared temperature CSV path (can be weather.dat).",
    )
    parser.add_argument(
        "--temperature-csv-template",
        default=None,
        help="Per-DSO temperature file template, e.g. 'C:/case/DSO_{dso}/weather.dat'.",
    )
    parser.add_argument(
        "--temperature-column",
        default=None,
        help="Temperature column name (shared by all DSOs). If omitted and the CSV has one column, that column is used.",
    )
    parser.add_argument(
        "--temperature-column-template",
        default=None,
        help="Per-DSO temperature column template, e.g. 'DSO_{dso}_temp'.",
    )
    parser.add_argument(
        "--temperature-unit",
        choices=["F", "C", "f", "c"],
        default="F",
        help="Temperature unit of the source file(s).",
    )
    parser.add_argument(
        "--dsos",
        default=None,
        help="Comma-separated DSO IDs to calibrate (default: all DSOs found in both baseline and actual CSVs).",
    )
    parser.add_argument(
        "--min-samples",
        type=int,
        default=72,
        help="Minimum samples required in each day type (weekday and weekend).",
    )
    parser.add_argument(
        "--include-diagnostics",
        action="store_true",
        help="Include fit RMSE and sample counts in the output JSON.",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output JSON file path for Q_bid_forecast_correction block.",
    )

    args = parser.parse_args()

    if not args.temperature_csv and not args.temperature_csv_template:
        raise ValueError("Provide --temperature-csv or --temperature-csv-template")

    requested_dsos = parse_dso_list(args.dsos)
    output_path = Path(args.output)
    output_payload, fits = calibrate_q_bid_forecast_correction(
        baseline_csv=Path(args.baseline_csv),
        actual_csv=Path(args.actual_csv),
        temperature_csv=Path(args.temperature_csv) if args.temperature_csv else None,
        temperature_csv_template=args.temperature_csv_template,
        temperature_column=args.temperature_column,
        temperature_column_template=args.temperature_column_template,
        temperature_unit=args.temperature_unit,
        dsos=requested_dsos,
        min_samples=args.min_samples,
        include_diagnostics=args.include_diagnostics,
        output=output_path,
    )

    print(f"Wrote calibrated coefficients for {len(fits)} DSO(s) -> {output_path}")
    print("DSO fit summary:")
    for dso in sorted(fits):
        wkday, wkend = fits[dso]
        print(
            f"  DSO_{dso}: "
            f"weekday(n={wkday.n_samples}, rmse={wkday.rmse:.4f}), "
            f"weekend(n={wkend.n_samples}, rmse={wkend.rmse:.4f})"
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
