#!/bin/bash

# sub="dsot"
# sub="flat-rate"
# sub="time-of-use"
sub="rob-don"

# if you have to remount the share drives

#export SIM_DATA=/mnt/dsot/run_outputs/Rates_Scenario/$sub
sudo umount -q /mnt/dsot
#if ! [ -d "$SIM_DATA" ]; then
#  sudo mount -t cifs //pnnlfs09.pnl.gov/sharedata37_op$/DSOT /mnt/dsot -o file_mode=0777,dir_mode=0777,username=$USER
#fi

export SIM_DATA=/mnt/post/Rates_Scenario/$sub
sudo umount -q /mnt/post
if ! [ -d "$SIM_DATA" ]; then
  sudo mount -t cifs //pnnlfs09.pnl.gov/sharedata13_op$/TSP_Rates /mnt/post -o file_mode=0777,dir_mode=0777,username=$USER
fi

#Extra if needed
#export SIM_DATA=/mnt/simdata/Rates_Scenario/$sub
sudo umount -q /mnt/simdata
#if ! [ -d "$SIM_DATA" ]; then
#  sudo mount -t cifs //pnnlfs09.pnl.gov/sharedata05_op$/PHOENIX /mnt/simdata -o file_mode=0777,dir_mode=0777,username=$USER
#fi
