name: Deploy Docker Image CI

on:
  push:
    branches: [ "dev", "test-workflow" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: login to hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: |
         cd scripts/docker
         ./build-images.sh

      # - name: Test
      #   run: |
      #     make venv
      #     source ./venv/bin/activate
      #     cd scripts
      #     ./integration_test.sh

#      - name: Publish
#        run: |
#          cd scripts/docker
#          ./push-images.sh