# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Lint and test

on:
  push:
    branches: [ "main", "develop", "test-workflows"]
  pull_request:
    branches: [ "main", "develop", "test-workflows"]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install uv 
        uv pip install ./src/tesp_support ruff pytest mypy --system
    - name: Lint with ruff
      run: |
        # Test code with ruff. This will check for syntax and runtime errors.
        # We will want to expand the scope as code is improved.
        # stop the build if there are Python syntax errors or undefined names
        # The values after --select are prefixes that match all error codes starting with those characters.
        # E9xx: Runtime (https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes)
        # F codes found at https://flake8.pycqa.org/en/latest/user/error-codes.html
        # F821: undefined name name
        # F822: undefined name name in __all__
        # F823: local variable name … referenced before assignment
        # F824: global name / nonlocal name is unused: name is never assigned in scope
        ruff check ./src --select=E9,F63,F7,F821,F822,F823  --statistics
        # exit-zero treats all errors as warnings.
        ruff check ./src --exit-zero --statistics
    # # Uncomment testing when tests are ready
    - name: Test with pytest
      run: |
        pytest ./src/tesp_support/test/api  # only api tests for now
    # # Uncomment type checking when code is ready
    # - name: Check types with mypy
    #   run: |
    #     mypy ./src/tesp_support/tesp_support/api
