# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Lint and test

on:
  push:
    branches: [ "main", "develop", "test-workflows"]
  pull_request:
    branches: [ "main", "develop", "test-workflows"]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -e ./src/tesp_support 
        pip install ruff pytest mypy

    - name: Lint with ruff
      run: |
        #       Test code with ruff. This will check for syntax and runtime errors.
        #       The values after --ignore prefixes that match all error codes starting with those characters.
        #       F codes found at https://flake8.pycqa.org/en/latest/user/error-codes.html
        #       F841    unused-variable
        #       E9xx: Runtime (https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes)
        #       E731    lambda-assignment
        ruff check ./src --ignore=F841,E731,UP031,SIM113,SIM115,DTZ001,DTZ005,DTZ007,BLE001,S110,TRY002,N999,RUF059,LOG015
        #       exit-zero treats all errors as warnings.
        # ruff check ./src --exit-zero --statistics
    
    - name: Check types with mypy
      run: |
        #       Stop the build if there are Python syntax errors and runtime errors.
        #       The values after --disable-error-code ignores match codes starting with those characters.
        mypy ./src/tesp_support/tesp_support/api --disable-error-code import-untyped --disable-error-code union-attr --disable-error-code attr-defined --disable-error-code import-not-found

    - name: Test with pytest
      run: |
        source ./tesp.env
        pytest ./src/tesp_support/test/api  # only api tests for now
