name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to test"
        required: true
        default: "staging"
        type: choice
        options:
        - staging
        - production

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Echo inputs
      run: echo "Testing in ${{ github.event.inputs.envrionment }}"