rm *.log
rm *.csv
rm *.out
rm *.xml
rm *.audit
rm broker_trace.txt
rm *metrics.json
rm *dict.json
rm *FNCS_Config.txt
rm *HELICS_gld_msg.json
rm *HELICS_substation.json
rm *Weather_Config.json
rm *substation.yaml
rm *.dat
rm output/*
rmdir output
rm *.idf
rm evchargerdet
rm *.bnd
